export const GET_USER_DETAILS_REQUEST = 'web-app/GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_SUCCESS = 'web-app/GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'web-app/GET_USER_DETAILS_SUCCESS';
